"""Convert public Golestan course tables into deterministic, static datasets.

The browser-compatible ``data.js`` keeps GitHub Pages deployment build-free.
The equivalent ``data.json`` is the canonical, tool-friendly representation.
Only text is retained from source cells; executable HTML is never copied.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

from bs4 import BeautifulSoup

DEFAULT_INPUT = Path("raw_data")
DEFAULT_JSON_OUTPUT = Path("assets/data/courses.json")
DEFAULT_JS_OUTPUT = Path("assets/js/data.js")
DEFAULT_MANIFEST_OUTPUT = Path("assets/data/manifest.json")

TRANSLATIONS = str.maketrans({
    "ي": "ی", "ك": "ک", "ة": "ه",
    "۰": "0", "۱": "1", "۲": "2", "۳": "3", "۴": "4",
    "۵": "5", "۶": "6", "۷": "7", "۸": "8", "۹": "9",
    "\u200c": " ",
})


def normalize_text(value: str | None) -> str:
    if not value:
        return ""
    return re.sub(r"\s+", " ", value.translate(TRANSLATIONS)).strip()


def safe_int(value: str | None) -> int:
    normalized = normalize_text(value)
    match = re.search(r"-?\d+", normalized)
    return int(match.group()) if match else 0


def normalized_schedule(cell: Any) -> str:
    lines = [
        normalize_text(re.sub(r"<[^>]*>", "", line))
        for line in cell.get_text("\n").splitlines()
    ]
    return "<br>".join(line for line in lines if line)


def parse_html_file(path: Path) -> tuple[list[dict[str, Any]], list[str]]:
    courses: list[dict[str, Any]] = []
    warnings: list[str] = []
    soup = BeautifulSoup(path.read_text(encoding="utf-8", errors="replace"), "html.parser")

    for row_number, row in enumerate(soup.find_all("tr"), start=1):
        cells = row.find_all("td")
        # Golestan export: the schedule/exam cell is index 13.
        if len(cells) < 14 or not normalize_text(cells[0].get_text()).isdigit():
            continue

        course = {
            "id": normalize_text(cells[4].get_text()),
            "name": normalize_text(cells[5].get_text()),
            "faculty": normalize_text(cells[1].get_text()),
            "group": normalize_text(cells[3].get_text()),
            "units": safe_int(cells[6].get_text()),
            "capacity": safe_int(cells[8].get_text()),
            "enrolled": safe_int(cells[9].get_text()),
            "gender": normalize_text(cells[11].get_text()),
            "prof": normalize_text(cells[12].get_text()),
            "time_html": normalized_schedule(cells[13]),
            "exam_text": normalize_text(cells[13].get_text(" ", strip=True)),
        }
        errors = validate_course(course)
        if errors:
            warnings.append(f"{path}:{row_number}: {', '.join(errors)}")
            continue
        courses.append(course)
    return courses, warnings


def validate_course(course: dict[str, Any]) -> list[str]:
    errors = []
    for field in ("id", "name", "faculty", "group"):
        if not course.get(field):
            errors.append(f"{field} is empty")
    # Thesis/dissertation entries can legitimately carry 18–20 units.
    if not isinstance(course.get("units"), int) or not 0 <= course["units"] <= 30:
        errors.append("units is outside 0..30")
    return errors


def build_dataset(input_dir: Path) -> tuple[list[dict[str, Any]], list[str]]:
    unique: dict[str, dict[str, Any]] = {}
    warnings: list[str] = []
    for path in sorted((*input_dir.glob("*.html"), *input_dir.glob("*.htm"))):
        parsed, file_warnings = parse_html_file(path)
        warnings.extend(file_warnings)
        for course in parsed:
            unique.setdefault(course["id"], course)
    return sorted(unique.values(), key=lambda item: item["id"]), warnings


def source_digest(input_dir: Path) -> str:
    digest = hashlib.sha256()
    for path in sorted((*input_dir.glob("*.html"), *input_dir.glob("*.htm"))):
        digest.update(path.name.encode("utf-8"))
        digest.update(path.read_bytes())
    return digest.hexdigest()


def write_outputs(
    courses: list[dict[str, Any]],
    json_output: Path,
    js_output: Path,
    manifest_output: Path,
    input_dir: Path,
) -> None:
    serialized = json.dumps(courses, ensure_ascii=False, indent=2)
    json_output.parent.mkdir(parents=True, exist_ok=True)
    js_output.parent.mkdir(parents=True, exist_ok=True)
    json_output.write_text(serialized + "\n", encoding="utf-8")
    js_output.write_text(
        "/** Generated by convert.py. Do not edit manually. */\n"
        f"const UNIVERSITY_DATA = {serialized};\n",
        encoding="utf-8",
    )
    manifest_output.parent.mkdir(parents=True, exist_ok=True)
    manifest_output.write_text(json.dumps({
        "schemaVersion": 1,
        "recordCount": len(courses),
        "sourceSha256": source_digest(input_dir),
        "generator": "convert.py",
    }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--json-output", type=Path, default=DEFAULT_JSON_OUTPUT)
    parser.add_argument("--js-output", type=Path, default=DEFAULT_JS_OUTPUT)
    parser.add_argument("--manifest-output", type=Path, default=DEFAULT_MANIFEST_OUTPUT)
    parser.add_argument("--check", action="store_true", help="validate without writing files")
    args = parser.parse_args()

    if not args.input.is_dir():
        parser.error(f"input directory does not exist: {args.input}")
    courses, warnings = build_dataset(args.input)
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    if not courses:
        print("error: no valid courses found", file=sys.stderr)
        return 1
    if not args.check:
        write_outputs(
            courses, args.json_output, args.js_output,
            args.manifest_output, args.input,
        )
    print(f"{len(courses)} unique courses; {len(warnings)} warnings")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
