import json
from pathlib import Path

from tools.data_pipeline.course_converter import (
    build_dataset,
    normalized_schedule,
    source_digest,
    validate_course,
)

ROOT = Path(__file__).resolve().parents[2]


def test_dataset_is_valid_unique_and_deterministic():
    courses, warnings = build_dataset(ROOT / "data/sources")
    assert not warnings
    assert len(courses) > 1_000
    assert len({course["id"] for course in courses}) == len(courses)
    assert courses == sorted(courses, key=lambda item: item["id"])
    assert all(not validate_course(course) for course in courses)


def test_generated_json_matches_source_data():
    expected, _ = build_dataset(ROOT / "data/sources")
    actual = json.loads((ROOT / "data/canonical/courses.json").read_text(encoding="utf-8"))
    assert actual == expected
    serialized = json.dumps(expected, ensure_ascii=False, indent=2)
    expected_wrapper = (
        "/** Generated by tools/data_pipeline/course_converter.py. Do not edit. */\n"
        f"const UNIVERSITY_DATA = {serialized};\n"
    )
    generated_wrapper = (
        ROOT / "apps/web/generated/course-offerings.generated.js"
    ).read_text(encoding="utf-8")
    assert generated_wrapper == expected_wrapper
    manifest = json.loads((ROOT / "data/canonical/manifest.json").read_text(encoding="utf-8"))
    assert manifest["schemaVersion"] == 1
    assert manifest["recordCount"] == len(expected)
    assert manifest["sourceSha256"] == source_digest(ROOT / "data/sources")


def test_schedule_never_copies_tags():
    class FakeCell:
        def get_text(self, separator):
            return "شنبه 08:00 - 10:00\n<script>alert(1)</script>"

    result = normalized_schedule(FakeCell())
    assert "<script>" not in result
