/**
 * Shared browser UI utilities loaded before page controllers.
 * این فایل قبل از تمام فایل‌های JS دیگر بارگذاری می‌شود.
 */

// ─── Theme ────────────────────────────────────────────────────────────────────
const Theme = {
    apply() {
        const saved = localStorage.getItem('theme') || 'dark';
        document.documentElement.setAttribute('data-theme', saved);
    },
    toggle() {
        const current = document.documentElement.getAttribute('data-theme');
        const next = current === 'light' ? 'dark' : 'light';
        document.documentElement.setAttribute('data-theme', next);
        localStorage.setItem('theme', next);
        return next;
    },
    current() {
        return document.documentElement.getAttribute('data-theme') || 'dark';
    }
};
Theme.apply();

// ─── Toast notifications ──────────────────────────────────────────────────────
const SafeDOM = Object.freeze({
    escape(value) {
        return String(value ?? '')
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    },
    setText(element, value) {
        if (element) element.textContent = String(value ?? '');
        return element;
    },
    /**
     * Tiny, deliberately restricted formatter. Input is escaped first; only
     * emphasis and line breaks generated by this function can become HTML.
     */
    formatPlainMarkdown(value) {
        return this.escape(value)
            .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
            .replace(/\*(.+?)\*/g, '<em>$1</em>')
            .replace(/\n/g, '<br>');
    },
});

const Toast = (() => {
    let container;
    function getContainer() {
        if (!container) {
            container = document.createElement('div');
            container.className = 'toast-container';
            document.body.appendChild(container);
        }
        return container;
    }

    const icons = { success: 'CircleCheck', error: 'CircleX', warning: 'CircleAlert', info: 'Info' };

    function show(message, type = 'info', duration = 4000) {
        const el = document.createElement('div');
        el.className = `toast ${type}`;
        el.setAttribute('role', type === 'error' ? 'alert' : 'status');
        const icon = document.createElement('span');
        icon.className = 'toast-icon';
        icon.innerHTML = AppIcons.svg(icons[type] || 'Info');
        const body = document.createElement('span');
        body.className = 'toast-msg';
        body.textContent = String(message);
        const close = document.createElement('button');
        close.className = 'toast-close';
        close.type = 'button';
        close.setAttribute('aria-label', 'بستن اعلان');
        close.innerHTML = AppIcons.svg('X');
        close.addEventListener('click', () => el.remove());
        el.append(icon, body, close);
        getContainer().appendChild(el);
        requestAnimationFrame(() => requestAnimationFrame(() => el.classList.add('show')));
        setTimeout(() => {
            el.classList.remove('show');
            setTimeout(() => el.remove(), 350);
        }, duration);
        return el;
    }

    return {
        show,
        success: (msg, dur) => show(msg, 'success', dur),
        error:   (msg, dur) => show(msg, 'error',   dur || 6000),
        warning: (msg, dur) => show(msg, 'warning', dur),
        info:    (msg, dur) => show(msg, 'info',    dur),
    };
})();

// ─── String normalization ─────────────────────────────────────────────────────
function normalizeStr(str) {
    return CourseDomain.normalizeText(str);
}

function toPersianNum(n) {
    return String(n).replace(/\d/g, d => '۰۱۲۳۴۵۶۷۸۹'[d]);
}

// ─── Day/schedule parsing ─────────────────────────────────────────────────────
const DAY_MAP = CourseDomain.DAY_MAP;
const DAY_NAMES = CourseDomain.DAY_NAMES;
const TIME_SLOTS = CourseDomain.TIME_SLOTS;

function getDayIndex(text) {
    return CourseDomain.getDayIndex(text);
}

function getTimeSlot(hour) {
    return CourseDomain.getTimeSlot(hour);
}

function parseSchedule(html) {
    return CourseDomain.parseSchedule(html);
}

function sessionsOverlap(sessA, sessB) {
    return CourseDomain.sessionsOverlap(sessA, sessB);
}

// ─── Debounce ─────────────────────────────────────────────────────────────────
function debounce(fn, delay = 300) {
    let timer;
    return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), delay); };
}

function selectTab(tab) {
    if (!tab) return;
    const tablist = tab.closest('[role="tablist"]');
    if (!tablist) return;
    const tabs = [...tablist.querySelectorAll(':scope > [role="tab"], :scope .tabs > [role="tab"]')];
    tabs.forEach(candidate => {
        const selected = candidate === tab;
        candidate.setAttribute('aria-selected', String(selected));
        candidate.tabIndex = selected ? 0 : -1;
    });
}

function enhanceTablists(root = document) {
    root.querySelectorAll('[role="tablist"]').forEach(tablist => {
        if (tablist.dataset.keyboardTabs === 'true') return;
        tablist.dataset.keyboardTabs = 'true';
        const tabs = [...tablist.querySelectorAll(':scope > [role="tab"], :scope .tabs > [role="tab"]')];
        if (!tabs.length) return;
        selectTab(tabs.find(tab => tab.getAttribute('aria-selected') === 'true') || tabs[0]);
        tabs.forEach(tab => {
            tab.addEventListener('click', () => selectTab(tab));
            tab.addEventListener('keydown', event => {
                const current = tabs.indexOf(tab);
                let next = null;
                if (event.key === 'Home') next = 0;
                if (event.key === 'End') next = tabs.length - 1;
                if (event.key === 'ArrowRight') next = (current - 1 + tabs.length) % tabs.length;
                if (event.key === 'ArrowLeft') next = (current + 1) % tabs.length;
                if (event.key === 'ArrowDown') next = (current + 1) % tabs.length;
                if (event.key === 'ArrowUp') next = (current - 1 + tabs.length) % tabs.length;
                if (next === null) return;
                event.preventDefault();
                tabs[next].focus();
                tabs[next].click();
            });
        });
    });
}

// ─── Faculty color palette ────────────────────────────────────────────────────
// رنگ‌ها عمداً از رنگ‌های status (قرمز conflict، نارنجی warning) دور هستند
const FACULTY_PALETTE = [
    '#3b82f6', '#10b981', '#8b5cf6', '#06b6d4',
    '#a855f7', '#2dd4bf', '#6366f1', '#22d3ee',
    '#34d399', '#818cf8', '#4ade80', '#38bdf8',
];

// Stable course colors keep sections visually distinct even when several belong
// to the same faculty. Conflict styling still uses the red status color.
const COURSE_PALETTE = [
    '#2563eb', '#059669', '#7c3aed', '#0891b2',
    '#c026d3', '#0d9488', '#4f46e5', '#0284c7',
    '#16a34a', '#9333ea', '#0f766e', '#0369a1',
];
