/**
 * Shared browser UI utilities loaded before page controllers.
 * این فایل قبل از تمام فایل‌های JS دیگر بارگذاری می‌شود.
 */

// ─── Theme ────────────────────────────────────────────────────────────────────
const Theme = {
    apply() {
        const saved = localStorage.getItem('theme') || 'dark';
        document.documentElement.setAttribute('data-theme', saved);
    },
    toggle() {
        const current = document.documentElement.getAttribute('data-theme');
        const next = current === 'light' ? 'dark' : 'light';
        document.documentElement.setAttribute('data-theme', next);
        localStorage.setItem('theme', next);
        return next;
    },
    current() {
        return document.documentElement.getAttribute('data-theme') || 'dark';
    }
};
Theme.apply();

// ─── Toast notifications ──────────────────────────────────────────────────────
const SafeDOM = Object.freeze({
    escape(value) {
        return String(value ?? '')
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    },
    setText(element, value) {
        if (element) element.textContent = String(value ?? '');
        return element;
    },
    /**
     * Tiny, deliberately restricted formatter. Input is escaped first; only
     * emphasis and line breaks generated by this function can become HTML.
     */
    formatPlainMarkdown(value) {
        return this.escape(value)
            .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
            .replace(/\*(.+?)\*/g, '<em>$1</em>')
            .replace(/\n/g, '<br>');
    },
});

const Toast = (() => {
    let container;
    function getContainer() {
        if (!container) {
            container = document.createElement('div');
            container.className = 'toast-container';
            document.body.appendChild(container);
        }
        return container;
    }

    const icons = { success: '✓', error: '✗', warning: '⚠', info: 'ℹ' };

    function show(message, type = 'info', duration = 4000) {
        const el = document.createElement('div');
        el.className = `toast ${type}`;
        el.setAttribute('role', type === 'error' ? 'alert' : 'status');
        const icon = document.createElement('span');
        icon.className = 'toast-icon';
        icon.textContent = icons[type] || '•';
        const body = document.createElement('span');
        body.className = 'toast-msg';
        body.textContent = String(message);
        const close = document.createElement('button');
        close.className = 'toast-close';
        close.type = 'button';
        close.setAttribute('aria-label', 'بستن اعلان');
        close.textContent = '×';
        close.addEventListener('click', () => el.remove());
        el.append(icon, body, close);
        getContainer().appendChild(el);
        requestAnimationFrame(() => requestAnimationFrame(() => el.classList.add('show')));
        setTimeout(() => {
            el.classList.remove('show');
            setTimeout(() => el.remove(), 350);
        }, duration);
        return el;
    }

    return {
        show,
        success: (msg, dur) => show(msg, 'success', dur),
        error:   (msg, dur) => show(msg, 'error',   dur || 6000),
        warning: (msg, dur) => show(msg, 'warning', dur),
        info:    (msg, dur) => show(msg, 'info',    dur),
    };
})();

// ─── String normalization ─────────────────────────────────────────────────────
function normalizeStr(str) {
    return CourseDomain.normalizeText(str);
}

function toPersianNum(n) {
    return String(n).replace(/\d/g, d => '۰۱۲۳۴۵۶۷۸۹'[d]);
}

// ─── Day/schedule parsing ─────────────────────────────────────────────────────
const DAY_MAP = CourseDomain.DAY_MAP;
const DAY_NAMES = CourseDomain.DAY_NAMES;
const TIME_SLOTS = CourseDomain.TIME_SLOTS;

function getDayIndex(text) {
    return CourseDomain.getDayIndex(text);
}

function getTimeSlot(hour) {
    return CourseDomain.getTimeSlot(hour);
}

function parseSchedule(html) {
    return CourseDomain.parseSchedule(html);
}

function sessionsOverlap(sessA, sessB) {
    return CourseDomain.sessionsOverlap(sessA, sessB);
}

// ─── Debounce ─────────────────────────────────────────────────────────────────
function debounce(fn, delay = 300) {
    let timer;
    return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), delay); };
}

// ─── Faculty color palette ────────────────────────────────────────────────────
// رنگ‌ها عمداً از رنگ‌های status (قرمز conflict، نارنجی warning) دور هستند
const FACULTY_PALETTE = [
    '#3b82f6', '#10b981', '#8b5cf6', '#06b6d4',
    '#a855f7', '#2dd4bf', '#6366f1', '#22d3ee',
    '#34d399', '#818cf8', '#4ade80', '#38bdf8',
];
